spring:
  datasource:
    url: jdbc:mysql://mysql:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password

  cloud:
    gateway:
      routes:
        - id: usuarios-route
          uri: lb://microservice-user
          predicates:
            - Path=/api/usuarios/**, /api/cuentas/**
          filters:
            - StripPrefix=0

        - id: monopatin-route
          uri: lb://microservice-monopatin
          predicates:
            - Path=/api/monopatines/**
          filters:
            - StripPrefix=0

        - id: tarifas-route
          uri: lb://microservice-tarifas
          predicates:
            - Path=/api/tarifas/**
          filters:
            - StripPrefix=0

        - id: facturacion-route
          uri: lb://microservice-facturacion
          predicates:
            - Path=/api/facturas/**
          filters:
            - StripPrefix=0

        - id: parada-route
          uri: lb://microservice-parada
          predicates:
            - Path=/api/paradas/**
          filters:
            - StripPrefix=0

        - id: viajes-route
          uri: lb://microservice-viajes
          predicates:
            - Path=/api/viajes/**
          filters:
            - StripPrefix=0
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30