spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: viaje_db
      # username: admin
      # password: password
      # authentication-database: admin

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Configuración de Feign Clients
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

# URLs de otros microservicios (para Feign)
microservices:
  monopatin:
    url: http://localhost:8082
  user:
    url: http://localhost:8083
  parada:
    url: http://localhost:8087
  facturacion:
    url: http://localhost:8085
  tarifa:
    url: http://localhost:8084


logging:
  level:
    com.microservices.viajes: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.cloud.openfeign: DEBUG